site_name: 齐鲁工业大学网络网络运维&网络与高性能计算协会
site_url: https://wlyw.qlu.edu.cn
nav:
    - 关于我们: about.md
    - 协会动态: news.md
    - 加入我们: join.md
    - 联系我们: chat.md
    - 友情链接: link.md
    - 信息系统导航: resources.md
    - 开源软件镜像站: https://mirrors.qlu.edu.cn
    - 校园MineCraft服务器: https://www.mc9g.cn
    - 信息系统常见故障答疑: 
      - 校园网: help/campusnetwork.md
      - 网络资源申请: help/apply.md
      - 校外VPN: help/vpn.md
      - 邮箱系统: help/mail.md
      - 正版软件: help/ms.md
      - 统一身份认证: help/sso.md
      - 一网通: help/os.md
      - 工大云盘: help/yunpan.md
      - 开源软件镜像站: help/mirrors.md

theme:
  name: material
